In [ ]:
import pandas as pd

# Sample data
data = {
    'Name': ['Chicken Breast', 'Tofu', 'Salmon', 'Almonds', 'Broccoli'],
    'Calories': [165, 76, 208, 575, 55],
    'Protein': [31, 8, 20, 21, 3.7]
}

# Create the DataFrame
df = pd.DataFrame(data)

df

             Name  Calories  Protein
0  Chicken Breast       165     31.0
1            Tofu        76      8.0
2          Salmon       208     20.0
3         Almonds       575     21.0
4        Broccoli        55      3.7

In [ ]:
df['Protein_per_Calorie'] = df['Protein'] / df['Calories']
df.sort_values(by='Protein_per_Calorie', ascending=False)

             Name  Calories  Protein  Protein_per_Calorie
0  Chicken Breast       165     31.0             0.187879
1            Tofu        76      8.0             0.105263
2          Salmon       208     20.0             0.096154
4        Broccoli        55      3.7             0.067273
3         Almonds       575     21.0             0.036522

In [ ]:
high_protein_low_cal = df[(df['Protein'] > 15) & (df['Calories'] < 250)]
df

,Name,Calories,Protein,Protein_per_Calorie,Serving,Total_Calories,Total_Protein
0,Chicken Breast,165,31.0,0.187879,1.5,247.5,46.5
1,Tofu,76,8.0,0.105263,1.0,76.0,8.0
2,Salmon,208,20.0,0.096154,0.5,104.0,10.0
3,Almonds,575,21.0,0.036522,0.0,0.0,0.0
4,Broccoli,55,3.7,0.067273,0.0,0.0,0.0

In [ ]:
#