<a href="https://colab.research.google.com/github/nouralanwar590-ui/some-pythons-coods/blob/main/Frames%20filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd

data = {
    'name': ['Xavier', 'Ann', 'Jana', 'Yi', 'Robin', 'Amal', 'Nori'],
    'city': ['Mexico City', 'Toronto', 'Prague', 'Shanghai',
             'Manchester', 'Cairo', 'Osaka'],
    'age': [41, 28, 33, 34, 38, 31, 37],
    'py-score': [88.0, 79.0, 81.0, 80.0, 68.0, 61.0, 84.0]
}

row_labels = [101, 102, 103, 104, 105, 106, 107]
df =pd.DataFrame(data=data, index=row_labels)

In [45]:
df.to_csv("data.csv")

In [46]:
df =pd.read_csv("data.csv", index_col=0)

In [47]:
df

       name         city  age  py-score
101  Xavier  Mexico City   41      88.0
102     Ann      Toronto   28      79.0
103    Jana       Prague   33      81.0
104      Yi     Shanghai   34      80.0
105   Robin   Manchester   38      68.0
106    Amal        Cairo   31      61.0
107    Nori        Osaka   37      84.0

In [48]:
#(Filtering)
filter1 = df["age"]<35
filter2 = df["py-score"]>70

df_filtered = df.where(filter1 & filter2)
df_filtered

     name      city   age  py-score
101   NaN       NaN   NaN       NaN
102   Ann   Toronto  28.0      79.0
103  Jana    Prague  33.0      81.0
104    Yi  Shanghai  34.0      80.0
105   NaN       NaN   NaN       NaN
106   NaN       NaN   NaN       NaN
107   NaN       NaN   NaN       NaN

In [52]:
df_filtered.dropna()

     name      city   age  py-score
102   Ann   Toronto  28.0      79.0
103  Jana    Prague  33.0      81.0
104    Yi  Shanghai  34.0      80.0

In [53]:
#(isin)
target_cities = ['Cairo', 'Osaka', 'Toronto']
city_filter = df[df['city'].isin(target_cities)]
print(city_filter)

     name     city  age  py-score
102   Ann  Toronto   28      79.0
106  Amal    Cairo   31      61.0
107  Nori    Osaka   37      84.0

In [54]:
high_achievers = df.loc[df['py-score'] >= 80, ['name', 'py-score']]
print(high_achievers)

       name  py-score
101  Xavier      88.0
103    Jana      81.0
104      Yi      80.0
107    Nori      84.0

In [59]:
df_row_str = input("Enter a row number from (0,6): ")
df_row_int = int(df_row_str)
selected_row = df.iloc[df_row_int]
print(selected_row)

Enter a row number from (0,6): 6
name         Nori
city        Osaka
age            37
py-score     84.0
Name: 107, dtype: object