<a href="https://colab.research.google.com/github/nouralanwar590-ui/some-pythons-coods/blob/main/Movie%20recommendation%20system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd

In [18]:
movies=pd.read_csv("/content/Netflix_Dataset_Movie.csv")
movies.head(10)

   Movie_ID  Year                          Name
0         1  2003               Dinosaur Planet
1         2  2004    Isle of Man TT 2004 Review
2         3  1997                     Character
3         4  1994  Paula Abdul's Get Up & Dance
4         5  2004      The Rise and Fall of ECW
5         6  1997                          Sick
6         7  1992                         8 Man
7         8  2004    What the #$*! Do We Know!?
8         9  1991      Class of Nuke 'Em High 2
9        10  2001                       Fighter

In [19]:
ratings =pd.read_csv("/content/Netflix_Dataset_Rating.csv")
ratings.head(10)

   User_ID  Rating  Movie_ID
0   712664       5         3
1  1331154       4         3
2  2632461       3         3
3    44937       5         3
4   656399       4         3
5   439011       1         3
6  1644750       3         3
7  2031561       4         3
8   616720       4         3
9  2467008       4         3

In [20]:
movies_ratings= pd.merge(movies,ratings)
movies_ratings.head(10)

   Movie_ID  Year       Name  User_ID  Rating
0         3  1997  Character   712664       5
1         3  1997  Character  1331154       4
2         3  1997  Character  2632461       3
3         3  1997  Character    44937       5
4         3  1997  Character   656399       4
5         3  1997  Character   439011       1
6         3  1997  Character  1644750       3
7         3  1997  Character  2031561       4
8         3  1997  Character   616720       4
9         3  1997  Character  2467008       4

In [21]:
movies_ratings= movies_ratings.pivot_table(index=['User_ID'],columns=['Name'],values='Rating')
movies_ratings.head()

Name,10,10 Things I Hate About You,101 Dalmatians II: Patch's London Adventure,11:14,13 Ghosts,18 Again,1984,2 Fast 2 Furious,200 Cigarettes,2010: The Year We Make Contact,...,Xena: Warrior Princess: Season 3,Xena: Warrior Princess: Series Finale,Y Tu Mama Tambien,Yellow Submarine,Yi Yi,Yojimbo,Young Black Stallion,Youngblood,Yu-Gi-Oh!: The Movie,Zorro
User_ID,,,,,,,,,,,,,,,,,,,,,
6,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134,NaN,5.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
movies["Name"][movies["Name"].str.contains("Wild")]

139                                       Lost in the Wild
219                Winston Churchill: The Wilderness Years
329                                            Wild Things
841                                     Reap the Wild Wind
1508                         National Lampoon's Van Wilder
                               ...
17374    Ocean Wilds: Realm of the Killer Whales/Sperm ...
17390                                   Wildboyz: Season 1
17482    Crocodile Hunter: Wildest Home Videos / Big Cr...
17614                                  Scarecrow Gone Wild
17765    Where the Wild Things Are and Other Maurice Se...
Name: Name, Length: 76, dtype: object

In [23]:
wild_ratings=movies_ratings["Wild Things"]
wild_ratings.head()

User_ID
6      NaN
7      NaN
79     NaN
97     NaN
134    5.0
Name: Wild Things, dtype: float64

In [24]:
similar_movies=movies_ratings.corrwith(wild_ratings)
similar_movies.head()

Name
10                                             0.295846
10 Things I Hate About You                     0.238126
101 Dalmatians II: Patch's London Adventure    0.243031
11:14                                          0.265127
13 Ghosts                                      0.263920
dtype: float64

In [25]:
similar_movies.sort_values(ascending=False)

Name
Wild Things                       1.000000
Poison Ivy 2                      0.441186
Players Club                      0.417944
Disturbing Behavior               0.384643
Jade                              0.382871
                                    ...
The Shop Around the Corner       -0.031849
The Saddest Music in the World   -0.037492
Cries and Whispers               -0.042256
In the Mood for Love             -0.053918
The Weather Underground          -0.061764
Length: 1342, dtype: float64